services: 
  mariadb:
    image: mariadb:1.0
    build: ./requirements/mariadb
    env_file: .env
    restart: unless-stopped
    networks:
      - inception-net
    volumes:
      - mariadb:/var/lib/mysql
    healthcheck:
      test: "mysql -uwordpress -pwordpress -e 'SELECT 1;'"
      interval: 2s
      timeout: 10s
      retries: 15

  wordpress:
    image: wordpress:1.0
    build: ./requirements/wordpress
    env_file: .env
    depends_on:
       mariadb:
         condition: service_healthy
    restart: on-failure
    networks:
      - inception-net
    volumes:
      - wordpress:/var/www/wordpress
        
  nginx:
    image: nginx:1.0
    build: ./requirements/nginx
    env_file: .env
    restart: on-failure
    depends_on:
      - wordpress
    networks:
      - inception-net
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/wordpress

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/mariadb

  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wordpress

networks:
  inception-net:
    driver: bridge
